// <auto-generated />
namespace HotelManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DescriptionIsAddedToAccomodationTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DescriptionIsAddedToAccomodationTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202004071701536_Description Is Added To Accomodation Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
